#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace meeting.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="meeting")]
	public partial class meeting_itemsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertT_meeting_item(T_meeting_item instance);
    partial void UpdateT_meeting_item(T_meeting_item instance);
    partial void DeleteT_meeting_item(T_meeting_item instance);
    #endregion
		
		public meeting_itemsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SqlConnection"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public meeting_itemsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public meeting_itemsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public meeting_itemsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public meeting_itemsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<T_meeting_item> T_meeting_items
		{
			get
			{
				return this.GetTable<T_meeting_item>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_meeting_items")]
	public partial class T_meeting_item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _item_id;
		
		private int _m_id;
		
		private string _item_state;
		
		private string _item_title;
		
		private System.Nullable<int> _item_time;
		
		private string _item_content;
		
		private string _item_files_url;
		
		private int _item_number;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onitem_idChanging(int value);
    partial void Onitem_idChanged();
    partial void Onm_idChanging(int value);
    partial void Onm_idChanged();
    partial void Onitem_stateChanging(string value);
    partial void Onitem_stateChanged();
    partial void Onitem_titleChanging(string value);
    partial void Onitem_titleChanged();
    partial void Onitem_timeChanging(System.Nullable<int> value);
    partial void Onitem_timeChanged();
    partial void Onitem_contentChanging(string value);
    partial void Onitem_contentChanged();
    partial void Onitem_files_urlChanging(string value);
    partial void Onitem_files_urlChanged();
    partial void Onitem_numberChanging(int value);
    partial void Onitem_numberChanged();
    #endregion
		
		public T_meeting_item()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int item_id
		{
			get
			{
				return this._item_id;
			}
			set
			{
				if ((this._item_id != value))
				{
					this.Onitem_idChanging(value);
					this.SendPropertyChanging();
					this._item_id = value;
					this.SendPropertyChanged("item_id");
					this.Onitem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_id", DbType="Int NOT NULL")]
		public int m_id
		{
			get
			{
				return this._m_id;
			}
			set
			{
				if ((this._m_id != value))
				{
					this.Onm_idChanging(value);
					this.SendPropertyChanging();
					this._m_id = value;
					this.SendPropertyChanged("m_id");
					this.Onm_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_state", DbType="NVarChar(20)")]
		public string item_state
		{
			get
			{
				return this._item_state;
			}
			set
			{
				if ((this._item_state != value))
				{
					this.Onitem_stateChanging(value);
					this.SendPropertyChanging();
					this._item_state = value;
					this.SendPropertyChanged("item_state");
					this.Onitem_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_title", DbType="NVarChar(50)")]
		public string item_title
		{
			get
			{
				return this._item_title;
			}
			set
			{
				if ((this._item_title != value))
				{
					this.Onitem_titleChanging(value);
					this.SendPropertyChanging();
					this._item_title = value;
					this.SendPropertyChanged("item_title");
					this.Onitem_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_time", DbType="Int")]
		public System.Nullable<int> item_time
		{
			get
			{
				return this._item_time;
			}
			set
			{
				if ((this._item_time != value))
				{
					this.Onitem_timeChanging(value);
					this.SendPropertyChanging();
					this._item_time = value;
					this.SendPropertyChanged("item_time");
					this.Onitem_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_content", DbType="NVarChar(MAX)")]
		public string item_content
		{
			get
			{
				return this._item_content;
			}
			set
			{
				if ((this._item_content != value))
				{
					this.Onitem_contentChanging(value);
					this.SendPropertyChanging();
					this._item_content = value;
					this.SendPropertyChanged("item_content");
					this.Onitem_contentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_files_url", DbType="NVarChar(MAX)")]
		public string item_files_url
		{
			get
			{
				return this._item_files_url;
			}
			set
			{
				if ((this._item_files_url != value))
				{
					this.Onitem_files_urlChanging(value);
					this.SendPropertyChanging();
					this._item_files_url = value;
					this.SendPropertyChanged("item_files_url");
					this.Onitem_files_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_number", DbType="Int NOT NULL")]
		public int item_number
		{
			get
			{
				return this._item_number;
			}
			set
			{
				if ((this._item_number != value))
				{
					this.Onitem_numberChanging(value);
					this.SendPropertyChanging();
					this._item_number = value;
					this.SendPropertyChanged("item_number");
					this.Onitem_numberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
