#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace meeting.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="meeting")]
	public partial class meetingDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertT_meeting(T_meeting instance);
    partial void UpdateT_meeting(T_meeting instance);
    partial void DeleteT_meeting(T_meeting instance);
    #endregion
		
		public meetingDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SqlConnection"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public meetingDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public meetingDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public meetingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public meetingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<T_meeting> T_meetings
		{
			get
			{
				return this.GetTable<T_meeting>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_meeting")]
	public partial class T_meeting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _m_id;
		
		private string _m_title;
		
		private string _m_theme;
		
		private string _m_abstract;
		
		private string _m_place;
		
		private System.DateTime _m_date;
		
		private string _m_compere;
		
		private string _m_people;
		
		private string _m_code;
		
		private string _m_state;
		
		private System.Nullable<int> _m_current_item;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onm_idChanging(int value);
    partial void Onm_idChanged();
    partial void Onm_titleChanging(string value);
    partial void Onm_titleChanged();
    partial void Onm_themeChanging(string value);
    partial void Onm_themeChanged();
    partial void Onm_abstractChanging(string value);
    partial void Onm_abstractChanged();
    partial void Onm_placeChanging(string value);
    partial void Onm_placeChanged();
    partial void Onm_dateChanging(System.DateTime value);
    partial void Onm_dateChanged();
    partial void Onm_compereChanging(string value);
    partial void Onm_compereChanged();
    partial void Onm_peopleChanging(string value);
    partial void Onm_peopleChanged();
    partial void Onm_codeChanging(string value);
    partial void Onm_codeChanged();
    partial void Onm_stateChanging(string value);
    partial void Onm_stateChanged();
    partial void Onm_current_itemChanging(System.Nullable<int> value);
    partial void Onm_current_itemChanged();
    #endregion
		
		public T_meeting()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int m_id
		{
			get
			{
				return this._m_id;
			}
			set
			{
				if ((this._m_id != value))
				{
					this.Onm_idChanging(value);
					this.SendPropertyChanging();
					this._m_id = value;
					this.SendPropertyChanged("m_id");
					this.Onm_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string m_title
		{
			get
			{
				return this._m_title;
			}
			set
			{
				if ((this._m_title != value))
				{
					this.Onm_titleChanging(value);
					this.SendPropertyChanging();
					this._m_title = value;
					this.SendPropertyChanged("m_title");
					this.Onm_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_theme", DbType="NVarChar(50)")]
		public string m_theme
		{
			get
			{
				return this._m_theme;
			}
			set
			{
				if ((this._m_theme != value))
				{
					this.Onm_themeChanging(value);
					this.SendPropertyChanging();
					this._m_theme = value;
					this.SendPropertyChanged("m_theme");
					this.Onm_themeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_abstract", DbType="NVarChar(MAX)")]
		public string m_abstract
		{
			get
			{
				return this._m_abstract;
			}
			set
			{
				if ((this._m_abstract != value))
				{
					this.Onm_abstractChanging(value);
					this.SendPropertyChanging();
					this._m_abstract = value;
					this.SendPropertyChanged("m_abstract");
					this.Onm_abstractChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_place", DbType="NVarChar(20)")]
		public string m_place
		{
			get
			{
				return this._m_place;
			}
			set
			{
				if ((this._m_place != value))
				{
					this.Onm_placeChanging(value);
					this.SendPropertyChanging();
					this._m_place = value;
					this.SendPropertyChanged("m_place");
					this.Onm_placeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_date", DbType="DateTime NOT NULL")]
		public System.DateTime m_date
		{
			get
			{
				return this._m_date;
			}
			set
			{
				if ((this._m_date != value))
				{
					this.Onm_dateChanging(value);
					this.SendPropertyChanging();
					this._m_date = value;
					this.SendPropertyChanged("m_date");
					this.Onm_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_compere", DbType="NVarChar(20)")]
		public string m_compere
		{
			get
			{
				return this._m_compere;
			}
			set
			{
				if ((this._m_compere != value))
				{
					this.Onm_compereChanging(value);
					this.SendPropertyChanging();
					this._m_compere = value;
					this.SendPropertyChanged("m_compere");
					this.Onm_compereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_people", DbType="NVarChar(MAX)")]
		public string m_people
		{
			get
			{
				return this._m_people;
			}
			set
			{
				if ((this._m_people != value))
				{
					this.Onm_peopleChanging(value);
					this.SendPropertyChanging();
					this._m_people = value;
					this.SendPropertyChanged("m_people");
					this.Onm_peopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_code", DbType="NVarChar(10)")]
		public string m_code
		{
			get
			{
				return this._m_code;
			}
			set
			{
				if ((this._m_code != value))
				{
					this.Onm_codeChanging(value);
					this.SendPropertyChanging();
					this._m_code = value;
					this.SendPropertyChanged("m_code");
					this.Onm_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_state", DbType="NVarChar(10)")]
		public string m_state
		{
			get
			{
				return this._m_state;
			}
			set
			{
				if ((this._m_state != value))
				{
					this.Onm_stateChanging(value);
					this.SendPropertyChanging();
					this._m_state = value;
					this.SendPropertyChanged("m_state");
					this.Onm_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_current_item", DbType="Int")]
		public System.Nullable<int> m_current_item
		{
			get
			{
				return this._m_current_item;
			}
			set
			{
				if ((this._m_current_item != value))
				{
					this.Onm_current_itemChanging(value);
					this.SendPropertyChanging();
					this._m_current_item = value;
					this.SendPropertyChanged("m_current_item");
					this.Onm_current_itemChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
